language: node_js
sudo: false
node_js:
  - node
cache: yarn
before_install:
  - npm install -g coveralls
script:
  - npm run build
  - npm run test
  - npm run lint
after_success:
  - npm run coverage
  - cat coverage/lcov.info | coveralls